# Generated by Django 6.0.2 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('Avaible', 'Avaible'), ('Booked', 'Booked'), ('Cleaning', 'Cleaning'), ('Closed', 'Closed')], default='Avaible', max_length=50),
            preserve_default=False,
        ),
    ]
